# Ansible playbook to install k3s on all the cluster nodes 
---
    
- hosts: k3s_master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s-master }

- hosts: k3s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s-worker }
