---

- hosts: k3s_worker
  gather_facts: yes
  become: yes
  roles:
    - role: teardown/k3s-worker
    - role: teardown/deletefiles

- hosts: k3s_master
  gather_facts: yes
  become: yes
  roles:
    - role: teardown/k3s-master
    - role: teardown/deletefiles
