---

- name: Delete rancher files
  shell: "rm -rf /var/lib/rancher"

- name: Delete files
  shell: |
    rm -rf /etc/ceph \
           /var/openebs \
           /etc/cni \
           /etc/kubernetes \
           /opt/cni \
           /opt/rke \
           /run/secrets/kubernetes.io \
           /run/calico \
           /run/flannel \
           /var/lib/calico \
           /var/lib/etcd \
           /var/lib/cni \
           /var/lib/kubelet \
           /var/lib/rancher/rke/log \
           /var/log/containers \
           /var/log/kube-audit \
           /var/log/pods \
           /var/run/calico
