---

- name: set k3s master host fact
  set_fact:
    k3s_master_host: "{{ groups['k3s_master'][0] }}"

- name: set master node token fact
  set_fact:
    k3s_master_token: "{{ hostvars[k3s_master_host]['k3s_node_token'].stdout }}"

- name: Install k3s on worker node
  shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_master_token }} INSTALL_K3S_EXEC=\" --docker \" sh -"

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: restarted
    enabled: yes
